### ISSUE TITLE
Cannot require file?

### ISSUE THREAD

**Issue by PikachuEXE** [rrrene/sparkr#3]
```
/Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require': cannot load such file -- sparkr (LoadError)
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/gems/sparkr-0.3.1/bin/sparkr:10:in `<top (required)>'
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/bin/sparkr:23:in `load'
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/bin/sparkr:23:in `<main>'
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `eval'
    from /Users/PikachuEXE/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by rrrene** [comment]
Unfortunately I could not reproduce this, but I have an idea and published a possible fix.

Could you reinstall `sparkr` with the new version `0.3.2` and retry?

**Comment by PikachuEXE** [comment]
OK it works fine now
